---
- name: Installing At Lunch Filebeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download metricbeat .deb file
    # Downloading System logs from Kibana
    # for more info use http://xxx.xxx.xxx.xxx:5601/app/kibana#/home/tutorial/systemLogs
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install Metricbeat .deb
    command: sudo dpkg -i metricbeat-7.4.0-amd64.deb

  - name: Drop in Metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Configure system module
    command: metricbeat modules enable docker

  - name: Setup metricbeat
    command: metricbeat setup

  #- name: Run metricbeat
   # command: sudo metricbeat -e

  - name: Start metricbeat service
    command: service metricbeat start

  #- name: Start metricbeat service on boot
   # command: systemctl start metricbeat
